name: Build Website Files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: Save files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-files
          path: dist
